[project]
name = "duckdb-server"
channels = ["conda-forge"]
description = "A Python DuckDB server for Mosaic"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.7,<4"

[pypi-dependencies]
duckdb-server = ">=0.11.0, <0.12"
