name: Build and Push Docker Images
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          for dockerfile in $(find . -name 'Dockerfile*'); do
            # Extract the variant name from the Dockerfile path
            variant=$(basename $dockerfile | sed 's/Dockerfile\.//')
            if [ "$variant" = "Dockerfile" ]; then
              variant="default"
            fi

            # Define the image name
            image_name="ghcr.io/${{ github.repository_owner }}/mosaic-duckdb-server-${variant}"

            # Build the Docker image
            docker build -f $dockerfile -t $image_name .

            # Push the Docker image
            docker push $image_name
          done